baseURL = "https://amirghaffari.com/"
title = "Amir Ghaffari"

theme = "codex"
hasCJKLanguage = false
enableEmoji = true
enableRobotsTXT = true
languageCode = "en-US"
defaultContentLanguage = "en"
copyright = "© Amir Ghaffari Heravi 2018 - {year}"
summaryLength = 100 # Custom cummary length, add <!--more--> in post file to custom split point
paginate = 10
googleAnalytics = "UA-76739238-11" #PLEASE CHANGE OR COMMENT THIS

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true

[params]
  author = "Amir Ghaffari Heravi" # You can also set author in post front matter individually
  subTitle = "full-stack web developer"

  # Word counter and read time indicator in post metadata
  showWordCounter = true
  showReadTime = true
  # License at the end of each post
  showLicense = false
  showToc = false

  # Open Graph & Twitter Card variables
  # You can also set description and images in post front matter individually
  description = "geek, programmer, full-stack developer."
  images = ["img/og.png"] # This will use the image called og.png in static/img folder

  twitter = "eamirgh"
  github = "eamirgh"
  email = "contact@amirghaffari.com"
