baseURL = "https://amirghaffari.com/"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-76739238-11"
hasCJKLanguage = false
languageCode = "en-US"
preserveTaxonomyNames = true
subTitle = "full-stack web developer"
theme = "LeaveIt"
title = "Amir Ghaffari"
[Permalinks]
posts = "/:filename/"
[blackfriday]
hrefTargetBlank = true
nofollowLinks = true
noreferrerLinks = true
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2
[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = true
disableSVG = false
disableXML = false
minifyOutput = true
[params]
author = "Amir Ghaffari"
avatar = "/uploads/avatar.webp"
description = "full-stack web developer"
keywords = "f"
showLicense = false
showToc = false
since = "2018"
subTitle = "full-stack web developer"
[params.social]
Email = "contact@amirghaffari.com"
GitHub = "eamirgh"
Instagram = "eamirgh"
Linkedin = "eamirgh"
Twitter = "eamirgh"
